################################
# Site Settings
################################
lang        : "pt-br"
logo        :
title       : "Maiquel Leonel"
description : "Meu blog sobre assuntos que gosto e repositório de coisas legais"
author      : "Maiquel Leonel"
email       : maiquel@maiquelleonel.com.br
baseurl     : "/" # the subpath of your site, e.g. /blog
url         : "http://blog.maiquelleonel.com.br"
date_format : "%-d %b %Y"
port        : 4000


################################
# Theme Settings
################################
#theme       : jekyll-theme-cayman
permalink   : /:title/

collections:
  docs:
    output: true
    permalink: /:collection/:path/

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Include/Exclude filetypes
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock


################################
# Analytics Settings
################################
google_analytics: UA-11722849-1
google_analytics_async: true # https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet
google_tag_manager: GTM-WBZD9NQ
facebook_pixel_id:


################################
# Jekyll Plugins
################################
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

# Jekyll SEO Tag Settings https://github.com/jekyll/jekyll-seo-tag
social:
  name: Maiquel Leonel
  links:
    - https://twitter.com/maiquelleonel
    - https://www.facebook.com/maiquelleonel
    #    - https://plus.google.com/u/0/+username

twitter:
  username: maiquelleonel

facebook:
  app_id:
  publisher:
  admins:

webmaster_verifications:
  google: jnc9hYXvS4KZFt-evHuY7a9IWyy79AT62lAK6qnXNYk
  bing:
  alexa:
  yandex:

# Jekyll Feed Settings https://github.com/jekyll/jekyll-feed
atom_feed:
    path: # Leave blank to use default (feed.xml)

# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
     - categories
     - tags
     - year
     - month
     - day
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
